---
title: "Hello world"
format:
    html:
        self-contained: true
---

> Testing Quarto

```{python}
from datetime import datetime

print(datetime.now())

import matplotlib.pyplot as plt

# Data for plotting
x = [1, 2, 3, 4, 5]
y = [1, 2, 3, 4, 5]

# Create the plot
plt.plot(x, y)

# Add title and labels
plt.title('Hello World Graph')
plt.xlabel('x-axis')
plt.ylabel('y-axis')

# Show the plot
plt.show()

import os
from google.cloud import bigquery
credentials_path = os.path.expanduser('~/.config/gcloud/application_default_credentials.json')

authenticated_locally = os.path.isfile(credentials_path)
running_in_dev = os.getenv('NAIS_CLUSTER_NAME', '').lower() == 'dev-gcp'
running_in_prod = os.getenv('NAIS_CLUSTER_NAME', '').lower() == 'prod-gcp'


# print todays time
print(datetime.now())

if running_in_dev:
    print("Running in dev")
elif running_in_prod:
    print("Running in prod")
else:
    print(os.getenv('NAIS_CLUSTER_NAME', ''))
    print("Running in neither dev nor prod")



if authenticated_locally or running_in_dev:  # Check if the file exists
    if authenticated_locally:
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credentials_path
    bigquery_client = bigquery.Client(project='flex-dev-2b16')

    query = """
    SELECT soknadstype FROM `flex-dev-2b16.korrigering_metrikk.andre_inntektskilder` LIMIT 10
    """

    query_job = bigquery_client.query(query)
    df = query_job.to_dataframe()
    print(f'dataframe length: {len(df)}')

    df.head()
else:

    print("Credentials file not found OR not running in dev. Functionality requiring credentials/devenv will be skipped.")

