schedule: "0 0 * * *"
nadaUrl: data.intern.dev.nav.no
quartoId: 4eff47a7-b3aa-4777-93ff-9a18edba2415 # https://data.intern.dev.nav.no/story/4eff47a7-b3aa-4777-93ff-9a18edba2415/index.html
gcpProjectId: flex-dev-2b16
environment: dev