cpu: 100m
memory: 256Mi
external-host:
  - data.intern.dev.nav.no
env:
  ENVIRONMENT: dev
  NADA_URL: data.intern.dev.nav.no
  QUARTO_ID: 4eff47a7-b3aa-4777-93ff-9a18edba2415
  GCP_TEAM_PROJECT_ID: flex-dev-2b16
