on:
  push:

permissions:
    contents: "read"
    id-token: "write"
    actions: "write"
jobs:
  build-and-push:
    name: Build and push GAR
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: flex
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  nais-deploy:
    needs: [build-and-push]
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@main
    with:
      image: ${{ needs.build-and-push.outputs.image }}
      prod-vars: nais/prod.yaml
      dev-vars: nais/dev.yaml
      nais-template: nais/naisjob.yaml
    secrets: inherit